export const MODULES = {
    USER: 'USER',
    ACCOUNTS: 'ACCOUNTS',
    CURRENCIES: 'CURRENCIES',
    ASSETS: 'ASSETS',
    SYMBOLS: 'SYMBOLS',
    ORDER_BOOK: 'ORDER_BOOK',
    LAST_TRADES: 'LAST_TRADES',
    CHART: 'CHART',
    MARKET: 'MARKET',
    HISTORY: 'HISTORY',
};

export const BLOCKED_MODULES = [
    MODULES.USER,
    MODULES.ACCOUNTS,
    MODULES.CURRENCIES,
    MODULES.ASSETS,
    MODULES.SYMBOLS,
    MODULES.MARKET,
]